### PR TITLE
fix: allow `sendCommand` to accept string command classes

### LINKED ISSUE #1219: [feat] Modify sendCommand to accept command class names in addition to CC IDs
Request to modify sendCommand so it'll accept the command class human readable names ("Multilevel Switch") in addition/in lieu of their command class numbers.

See discussion in #1196 .  

(copy pasta from there)

@robertsLando I think it would be good if the mqtt API not only accepted the CC IDs (numbers) but also their names as defined in node-zwave-js. So for a startLevelChange the command could look like this:

{ "args": [
  {
    "nodeId": 23,
    "commandClass": "Multilevel Switch",
    "endpoint": 0,
  },
  "startLevelChange",
]}

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #1219

### CODE REVIEW

File: lib/ZwaveClient.js [hunk 1]
```diff
@@ -1425,7 +1425,7 @@ class ZwaveClient extends EventEmitter {
   /**
    * Send a command
    *
-   * @param {{nodeId: number, endpoint: number, commandClass: number}} ctx context to get the instance to send the command
+   * @param {{nodeId: number, endpoint: number, commandClass: number | string}} ctx context to get the instance to send the command
```
Comment (AlCalzone) [inline lib/ZwaveClient.js:1428]: The correct type for `commandClass` would be: `CommandClasses | keyof typeof CommandClasses`, where `CommandClasses` is the enum from `zwave-js`.

File: lib/ZwaveClient.js [hunk 2]
```diff
@@ -1454,8 +1454,12 @@ class ZwaveClient extends EventEmitter {
         )
       }
 
+      const commandClass = isNaN(ctx.commandClass)
+        ? CommandClasses[ctx.commandClass]
+        : ctx.commandClass
```
Comment (AlCalzone) [inline lib/ZwaveClient.js:1459]: I'd turn this around:
```js
      const commandClass = typeof ctx.commandClass === "number"
        ? ctx.commandClass
        : CommandClasses[ctx.commandClass]
```

**Comment by robertsLando** [comment]
@AlCalzone Implemented in a new PR, thanks
