### PR TITLE
fix(hass): improved climates discovery

### LINKED ISSUE #607: [question] Danfoss LC13 not discovering all values
Hello
I have 3 different Danfoss Living Connect Z Thermostat. For two of them all values are identified properly and I can see them in the ZWaveJS2MQTT Control Panel. This are:
climate_thermostat
sensor_battery_level
binary_sensor_battery_islow

But for one I can only:
sensor_battery_level
binary_sensor_battery_islow

I've installed this on RPI3 using this instruction: https://flemmingss.com/how-to-set-up-zwavejs2mqtt-on-a-raspberry-pi-and-integrate-it-with-home-assistant/
My question is, how can I get the other values to show up as home assistant devices?
Cheers,

image
image

### PR DESCRIPTION
**Pull request by billiaz**
This PR fixes climate thermostats (like Danfoss LC-13).

Fixes #607

### CODE REVIEW

File: lib/Gateway.js [hunk 1]
```diff
@@ -1469,9 +1462,15 @@ Gateway.prototype.discoverClimates = function (node) {
...
-    config.discovery_payload.current_temperature_topic = temperatureId
+    // set empty config.values
+    config.values = []
 
-    config.values = [temperatureId]
+    if (temperatureId) {
+      config.discovery_payload.current_temperature_topic = temperatureId
+      config.values.push(temperatureId)
+    } else {
+      config.discovery_payload.current_temperature_template = undefined
```
Comment (robertsLando) [inline lib/Gateway.js:1472]:
```suggestion
      delete config.discovery_payload.current_temperature_template
      delete config.discovery_payload.current_temperature_topic
```

File: lib/Gateway.js [hunk 2]
```diff
@@ -1548,9 +1547,11 @@ Gateway.prototype.discoverClimates = function (node) {
         config.setpoint_topic[Object.keys(config.setpoint_topic)[0]]
     } else {
       config.default_setpoint = setpoints[0]
+      config.discovery_payload.modes = undefined
+      config.discovery_payload.mode_state_template = undefined
```
Comment (robertsLando) [inline lib/Gateway.js:1551]:
```suggestion
      delete config.discovery_payload.modes
      delete config.discovery_payload.mode_state_template
```

File: lib/Gateway.js [hunk 3]
```diff
@@ -1548,9 +1547,11 @@ Gateway.prototype.discoverClimates = function (node) {
...
     }
 
-    if (actions) {
+    if (!actions.length === 0) {
```
Comment (robertsLando) [inline lib/Gateway.js:1554]:
```suggestion
    if (actions.length > 0) {
```

**Review by robertsLando — CHANGES_REQUESTED** [review]

**Review by robertsLando — APPROVED** [review]
LGTM
