### PR TITLE
fix: detect driver failed and restart

### LINKED ISSUE #1246: [bug] zwavejs2mqtt does not reconnect if the serial port (TCP socket) is closed
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.3.0
zwave-js version: 7.5.0

### Describe the bug

In #1167, a problem with detecting a dropped TCP socket connection to the serial device was reported and fixed in https://github.com/zwave-js/node-zwave-js/pull/2601. However, the application needs to handle the lost connection. For now, the state is "Driver: The socket closed unexpectedly". IMHO, zwavejs2mqtt should try to auto-reconnect in this case, as the connection might become available (this could also be a configuration option, like auto-reconnect interval).

It finally reconnects if I go to Settings and click on "Save".

### To Reproduce

1. Connect the Z-Wave dongle via ser2net
2. Stop ser2net
3. Wait for the lost connection in zwavejs2mqtt
4. Restart ser2net

### Expected behavior

After 4., the connection should be auto-restored.

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #1246
Fixes https://github.com/zwave-js/node-zwave-js/issues/2609

### CODE REVIEW

File: lib/ZwaveClient.js [hunk 1]
```diff
@@ -1750,11 +1756,22 @@ class ZwaveClient extends EventEmitter {
     logger.info(`Scanning network with homeid: ${homeHex}`)
   }
 
-  _onDriverError (error) {
+  async _onDriverError (error) {
     this.error = 'Driver: ' + error.message
     this.status = ZWAVE_STATUS.driverFailed
     this._updateControllerStatus(this.error)
 
+    if (error instanceof ZWaveErrorCodes.Driver_Failed) {
```
Comment (AlCalzone) [inline lib/ZwaveClient.js:1764]:
```suggestion
    if (error.code === ZWaveErrorCodes.Driver_Failed) {
```

Comment (AlCalzone) [reply lib/ZwaveClient.js:1764]: Error is `instanceof ZWaveError`

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: lib/ZwaveClient.js (hunk 1 above)
Comment (robertsLando) [reply lib/ZwaveClient.js]: Right...
