### PR TITLE
fix: binary sensor notification changes break double taps and other events

### LINKED ISSUE #421: [bug] recent binary sensor changes break double taps and other undefined notification events
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

#396 changed the manner in which binary sensors with only two states are handled. As a result, double tap events no longer work because they are not a valueId.list and the nesting of the else statement prevents a sensor_generic being setup. While investigating this, I realized that fixing it by re-nesting the else statement to the correct position broke other notification events that ARE a valueId.list but whose length is longer than 2.

### To Reproduce

1. Run the most recent dev image or build from master

### Expected behavior

Double taps should keep working as they were

### Additional context

MQTT log:

```
2021-02-01 20:40:37.572 INFO ZWAVE: Node 3 is alive
2021-02-01 20:40:37.725 ERROR GATEWAY: Error while discovering value 3-32-0-event of node 3: Cannot read property 'discovery_payload' of undefined Cannot read property 'discovery_payload' of undefined
TypeError: Cannot read property 'discovery_payload' of undefined
    at Gateway.discoverValue (/usr/src/app/lib/Gateway.js:1828:25)
    at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:358:12)
    at ZwaveClient.emit (events.js:314:20)
    at ZwaveClient.EventEmitter.emit (domain.js:483:12)
    at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:317:10)
    at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:361:16)
    at ZWaveNode.emit (events.js:326:22)
    at ZWaveNode.EventEmitter.emit (domain.js:483:12)
    at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:424:19)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:217:10
    at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:255:17)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
    at Proxy.Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
    at ZWaveNode.onStatusChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:366:21)
```

After re-nesting the else statement, I get:

```
2021-02-02 00:02:05.563 ERROR GATEWAY: Error while discovering value 77-113-0-Power Management-Battery maintenance status of node 77: Cannot read property 'discovery_payload' of undefined Cannot read property 'discovery_payload' of undef$
TypeError: Cannot read property 'discovery_payload' of undefined
    at Gateway.discoverValue (/usr/src/app/lib/Gateway.js:1828:25)
    at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:358:12)
    at ZwaveClient.emit (events.js:314:20)
    at ZwaveClient.EventEmitter.emit (domain.js:483:12)
    at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:317:10)
    at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:361:16)
    at ZWaveNode.emit (events.js:326:22)
    at ZWaveNode.EventEmitter.emit (domain.js:483:12)
    at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:424:19)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:217:10
    at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:255:17)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
    at Proxy.Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
    at ZWaveNode.onStatusChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:366:21)
```
and:

```
2021-02-02 00:03:34.918 ERROR GATEWAY: Error while discovering value 120-113-0-Heat Alarm-Heat sensor status of node 120: Cannot read property 'discovery_payload' of undefined Cannot read property 'discovery_payload' of undefined
TypeError: Cannot read property 'discovery_payload' of undefined
    at Gateway.discoverValue (/usr/src/app/lib/Gateway.js:1828:25)
    at Gateway.onNodeStatus (/usr/src/app/lib/Gateway.js:358:12)
    at ZwaveClient.emit (events.js:314:20)
    at ZwaveClient.EventEmitter.emit (domain.js:483:12)
    at ZwaveClient.onNodeStatus (/usr/src/app/lib/ZwaveClient.js:317:10)
    at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:361:16)
    at ZWaveNode.emit (events.js:326:22)
    at ZWaveNode.EventEmitter.emit (domain.js:483:12)
    at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:424:19)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:217:10
    at Interpreter.update (/usr/src/app/node_modules/xstate/lib/interpreter.js:255:17)
    at /usr/src/app/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/usr/src/app/node_modules/xstate/lib/scheduler.js:44:14)
    at Proxy.Interpreter.send (/usr/src/app/node_modules/xstate/lib/interpreter.js:121:29)
    at ZWaveNode.onStatusChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:366:21)
```

### PR DESCRIPTION
**Pull request by blhoward2**
Closes #421 and https://github.com/zwave-js/node-zwave-js/issues/1555. Recent changes to how binary sensors are created for notification events (#396) broke double tap via basic set events because of the nesting of the else statement (valueId.list was not true, so the if block in which sensor_generic was setup was never entered). Fixing that caused other devices to have the undefined error where valueId.list was true, but the value.state.length was not 2. 

I changed the top-level if statement to only enter if valueId.list is true && valueIf.states.length === 2. In all other cases the else block should be entered to setup a sensor_generic. I have tested this and it works fine now. It is also much cleaner and gets rid of the nested if statement.

While reviewing this, I realized that we were defining a bunch of binary_sensor types in configurations.ts that are never used. We were only ever loading binary_sensor_contact, then overriding the object_id and device class depending on the case. We never used any of the others. I've now changed this so we setup a generic binary sensor, with device class None, and then we override the objectId and device class if appropriate. @billiaz Correct me if I'm wrong here, but I did a grep and the others aren't referenced anywhere else but in configurations.ts.

### CODE REVIEW

**Comment by blhoward2** [comment]
@crzykidd @jarrettv Please see if this fixes your double-tap errors so I know which device files need to be amended.

**Comment by billiaz** [comment]
Can you help me understand what breaks? I would like to see the example of it.

File: hass/configurations.js [hunk 1]
```diff
@@ -3,134 +3,14 @@
...
-  binary_sensor_motion: {
+  binary_sensor: {
     type: 'binary_sensor',
-    object_id: 'motion',
+    object_id: 'event',
     discovery_payload: {
       payload_on: true,
       payload_off: false,
       value_template: '{{ value_json.value }}',
-      device_class: 'motion'
```
Comment (billiaz) [inline hass/configurations.js:13]: I would not touch thsi file, ti breaks completely the binary sensors logic. which is using the binary_sensor_<type>

File: lib/Gateway.js [hunk 2]
```diff
@@ -1631,82 +1631,78 @@ Gateway.prototype.discoverValue = function (node, vId) {
...
-                cfg.discovery_payload.icon = 'mdi:motion-sensor'
-                break
-              default:
-                cfg.discovery_payload.icon = 'mdi:alarm-light'
-            }
-            cfg.discovery_payload.value_template = getMappedStateTemplate(
-              valueId.states,
-              valueId.default
-            )
+        if (valueId.list && valueId.states.length === 2) {
```
Comment (billiaz) [inline lib/Gateway.js:1634]: this is nice, simple change, might need refactoring once we introduce the > 2 states

File: lib/Gateway.js [hunk 3]
```diff
@@ -1631,82 +1631,78 @@ Gateway.prototype.discoverValue = function (node, vId) {
...
+            // on property basis... user friendly
+            case 'Sensor status':
+              switch (valueId.propertyName) {
+                case 'Smoke Alarm':
+                  cfg.discovery_payload.device_class = 'smoke'
+                  break
+                case 'Water Alarm':
+                  cfg.discovery_payload.device_class = 'moisture'
+                  break
+                default:
```
Comment (billiaz) [inline lib/Gateway.js:1675]: same here i miss `None` class.

File: lib/Gateway.js [hunk 4]
```diff
@@ -1631,82 +1631,78 @@ Gateway.prototype.discoverValue = function (node, vId) {
...
+              }
+              cfg.object_id = valueId.propertyName
+              break
+            case 'Water Alarm':
+              cfg.discovery_payload.device_class = 'moisture'
+              break
+            default:
```
Comment (billiaz) [inline lib/Gateway.js:1682]: and here `None` is missing.

File: lib/Gateway.js (hunk 3 above)
Comment (blhoward2) [reply lib/Gateway.js:1675]: You don't need it because None is setup as the default up above for binary_sensor.

File: hass/configurations.js (hunk 1 above)
Comment (blhoward2) [reply hass/configurations.js:13]: We aren't ever using the other ones though. You only ever load binary_sensor_contact above the if block.

Comment (billiaz) [reply hass/configurations.js:13]: In this line you can see the second use of this file.
https://github.com/zwave-js/zwavejs2mqtt/blob/3d77e853a826bf990fd6b6861ae04e1d535271a1/lib/Gateway.js#L1602

This is not going to break all binary sensors.

Adding the support for the None change. 
you could probably create a sensor `binary_sensor_none` and use that for notifications to keep the Later `None` removal

Comment (blhoward2) [reply hass/configurations.js:13]: Ah, ok. I'll stet that back tomorrow.

**Comment by blhoward2** [comment]
@robertsLando hold off on merging. I need to revert the changes to the binary sensor definitions.

**Comment by blhoward2** [comment]
> Can you help me understand what breaks? I would like to see the example of it.

I DMd you my json on slack. My log is in #421

**Comment by blhoward2** [comment]
@billiaz Do you agree that I should add back the binary sensor definitions, but we should move the cfg = and objectId = lines down under each case (referencing the correct definition) so that their value template gets picked up?

**Comment by robertsLando** [comment]
Let me know when this is ready for a review

**Comment by robertsLando** [comment]
We should ensure device calsses are all allowed. a user reported me some discovery breaks after last changes.

Allowed device classes are: 

```
// sensor binary
 [
          // sensor binary: https://www.home-assistant.io/integrations/binary_sensor/
          'battery',
          'cold',
          'connectivity',
          'door',
          'garage_door',
          'gas',
          'heat',
          'light',
          'lock',
          'moisture',
          'motion',
          'moving',
          'occupancy',
          'opening',
          'plug',
          'power',
          'presence',
          'problem',
          'safety',
          'smoke',
          'sound',
          'vibration',
          'window'
        ]
    
        // sensor multilevel and meters: https://www.home-assistant.io/integrations/sensor/
        return [
          'battery',
          'humidity',
          'illuminance',
          'signal_strength',
          'temperature',
          'power',
          'power_factor',
          'pressure',
          'timestamp',
          'current',
          'energy',
          'voltage'
        ]
     
        // multilevel switch: home-assistant.io/integrations/cover/
         [
          'awning',
          'blind',
          'curtain',
          'damper',
          'door',
          'garage',
          'gate',
          'shade',
          'shutter',
          'window'
        ]    
```

We could create enums for this.

File: hass/configurations.js (hunk 1 above)
Comment (robertsLando) [reply hass/configurations.js:13]: I like this change, it cleans up some repeated values, I would instead fix the other to use the correct device class

**Review by robertsLando — CHANGES_REQUESTED** [review]

File: hass/configurations.js (hunk 1 above)
Comment (billiaz) [reply hass/configurations.js:13]: I got some idea how we can do it! I will send a PR to @blhoward2 's branch for review/merging!

**Comment by AlCalzone** [comment]
From reading the HA Discord I'm getting the feeling you're doing the same work as the HA devs. Might be worth to join forces factor that out somehow?
/cc @marcelveldt

**Comment by blhoward2** [comment]
What is being duplicated? I scanned discord and didn't see it.

**Comment by marcelveldt** [comment]
> What is being duplicated? I scanned discord and didn't see it.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/zwave_js/binary_sensor.py#L66

We ended up using these mappings.

**Comment by AlCalzone** [comment]
Yesterday there was a discussion about binary sensors for notifications.
Didn't read it in depth though. Just a thought on my part - maybe a think tank would help everyone working on discovery.

**Comment by robertsLando** [comment]
MQTT discovery is still there just because some users tell me they prefer that for the possiblity to manually edit/fix entities created, that said I really don't mind if somone uses MQTT discovery or the hass addon, I just try to keep that updated to give users an alternative :) 

Today a user was having a problem with climates and I told him to use the hass addon and that fixed his problems, I think this can be helpful for both

**Comment by blhoward2** [comment]
This looks right to me but that is more what @billiaz was working on. My changes are for where a binary sensor doesn't actually work...a notification event on the basic set that isn't distinguishable as a type (double tap) because we're treating a basic set on/off as a notification for double taps. Here it was an issue with the catch-all that sets up a generic sensor to read the 0/255, but we should make sure the server handles the basic set notification too.

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

File: hass/configurations.js [hunk 5]
```diff
@@ -3,134 +3,14 @@
...
-  },
-  binary_sensor_battery_low: {
-    type: 'binary_sensor',
-    object_id: 'battery_low',
-    discovery_payload: {
-      payload_on: true,
-      payload_off: false,
-      value_template: '{{ value_json.value }}',
-      device_class: 'battery'
+      device_class: 'None'
```
Comment (robertsLando) [inline hass/configurations.js:13]: @blhoward2 remove this, `None` is not a valid device class

**Review by robertsLando — CHANGES_REQUESTED** [review]

File: hass/configurations.js [hunk 6]
```diff
@@ -3,134 +3,14 @@
...
-    type: 'binary_sensor',
-    object_id: 'tamper',
-    discovery_payload: {
-      payload_on: true,
-      payload_off: false,
-      value_template: '{{ value_json.value }}',
-      device_class: 'safety'
-    }
-  },
-  binary_sensor_alarm: {
```
Comment (robertsLando) [inline hass/configurations.js:106]: This is used here: https://github.com/zwave-js/zwavejs2mqtt/blob/12bb55d9025bd6ba513028f414ba1f90adb933be/lib/Gateway.js#L1663

File: hass/configurations.js [hunk 7]
```diff
@@ -3,134 +3,14 @@
...
-    type: 'binary_sensor',
-    object_id: 'router',
-    discovery_payload: {
-      payload_on: true,
-      payload_off: false,
-      value_template: '{{ value_json.value }}',
-      device_class: 'connectivity'
-    }
-  },
-  binary_sensor_battery_low: {
```
Comment (robertsLando) [inline hass/configurations.js:126]: This is used here: https://github.com/zwave-js/zwavejs2mqtt/blob/12bb55d9025bd6ba513028f414ba1f90adb933be/lib/Gateway.js#L1842

**Review by robertsLando — DISMISSED** [review]
Remember to fix the battery and alarm sensors to use the default binary sensor and by edit the device class

**Comment by blhoward2** [comment]
@robertsLando With @billiaz great changes, I think this is ready unless he has other changes. I built a new docker and confirmed double tap is still working after today's changes.

**Review by robertsLando — APPROVED** [review]
LGTM. Thanks @billiaz @blhoward2

**Comment by billiaz** [comment]
@robertsLando @blhoward2 I suggest to see some more improvements on this PR posted as PR on the modifying branch.
https://github.com/blhoward2/zwavejs2mqtt/pull/3
